services:
  redmine:
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redmine-plugin-test
    volumes:
      - ./:/usr/src/redmine/plugins/redmine_github_collaborate
